using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Views.Locations.Warehouse;
using CatoriShared.AnimationHelpers;
using System.Windows.Input;

namespace CatoriApp.Game.Controllers.Locations.Warehouse
{
    public sealed class WarehouseViewController : CatoriApp.Game.Controllers.ControllerAnimateLayoutsBase
    {
        private const string RightStorePath="RightProductStorePath";
        private const string LeftStorePath="LeftProductStorePath";
        private readonly WarehouseView _view;
        private bool _routeNextToRight=true;

        public WarehouseViewController(WarehouseView view)
            : base()
        {
            _view = view ?? throw new ArgumentNullException(nameof(view));
            LoadWarehouseImage();
            _view.PreviewKeyDown += View_PreviewKeyDown;
            // These paths are destinations of the warehouse entry path, not roots.
            _productionSession.AddDeferredPath(RightStorePath);
            _productionSession.AddDeferredPath(LeftStorePath);
        }

        private void View_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if(e.Key!=Key.R||!Keyboard.Modifiers.HasFlag(ModifierKeys.Control))return;
            StartProduction();
            e.Handled=true;
        }

        public void StartProduction()
        {
            _productionSession.StartRoots();
        }
        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            if(!IsEntryPath(message.AnimationName))return;

            string destination=ResolveDestination(message.PartName);
            var handle=_productionSession.Handles.FirstOrDefault(candidate=>
                string.Equals(candidate.AnimationName,destination,StringComparison.OrdinalIgnoreCase));
            handle?.Start();
        }

        private string ResolveDestination(string? partName)
        {
            if(partName?.Contains("Right",StringComparison.OrdinalIgnoreCase)==true)return RightStorePath;
            if(partName?.Contains("Left",StringComparison.OrdinalIgnoreCase)==true)return LeftStorePath;

            string destination=_routeNextToRight?RightStorePath:LeftStorePath;
            _routeNextToRight=!_routeNextToRight;
            return destination;
        }

        private static bool IsEntryPath(string animationName)
        {
            return string.Equals(animationName, "DroneEntry", StringComparison.OrdinalIgnoreCase)
                      || string.Equals(animationName, "EntryLoadPath", StringComparison.OrdinalIgnoreCase)
                      || string.Equals(animationName, "EntryoadPath", StringComparison.OrdinalIgnoreCase);
        }

        private void LoadWarehouseImage()
        {
            string imagePath = Imagehelper.GetImagePath(System.IO.Path.Combine(
                GlobalAllApps.ImageFolder, "Warehouses", "WarehouseInterior.png"));
            _view.WarehouseImage.Source = UIUtility.GetImageControl(imagePath, 100, 100, 0).Source;
            var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository()
                .GetByNameAsync("WarehouseImage").GetAwaiter().GetResult()
                ?? throw new InvalidOperationException(
                    "Location 'WarehouseImage' was not found in the game database. Export the Studio location before running generated code.");
            _locationId = generatedLocation.LocationId;
            SetupAnimations();
        }

        public void Close()
        {
            Dispose();
            _view.Close();
        }

        public override void Dispose()
        {
            _view.PreviewKeyDown-=View_PreviewKeyDown;
            base.Dispose();
        }

        // ============================================================
        //  GENERATED BY CATORI.STUDIO.DEV
        //
        //  DO NOT FIX GENERATED CODE HERE.
        //
        //  If this code is incorrect, fix the generator in Studio
        //  and regenerate this file.
        // ============================================================
        // Generated code for location layout items
        ProductUC droneWBox_part48_productUC;
        PathAnimationHandle _pathHandlerEntryoadPath;
        ProductUC unassigned_part49_productUC;
        PathAnimationHandle _pathHandlerRightProductStorePath;
        ProductUC unassigned_part50_productUC;
        PathAnimationHandle _pathHandlerLeftProductStorePath;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
        };
        private readonly PathAnimationSession _productionSession = new();

        private void SetupAnimations()
        {
            try
            {
                var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("WarehouseImage").GetAwaiter().GetResult()
                    ?? throw new InvalidOperationException("Location 'WarehouseImage' was not found in the game database. Export the Studio location before running generated code.");
                _locationId = generatedLocation.LocationId;
                var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
                var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
                PathAnimationOptions? options = new PathAnimationOptions();
                options.Duration = TimeSpan.FromSeconds(2);
                options.InitialScale = .73;
                options.AutoStart = false;
                options.ControlWidth = 100;
                options.ControlHeight = 100;
                PathAnimationOptions droneOptions = new PathAnimationOptions();
                droneOptions.Duration = TimeSpan.FromSeconds(2);
                droneOptions.InitialScale = .73;
                droneOptions.AutoStart = false;
                droneOptions.RotateWithPath = false;
                droneOptions.ControlWidth = 100;
                droneOptions.ControlHeight = 100;
                productionPaths.TryGetValue("EntryoadPath", out var productionPathEntryoadPath);
                // Assigned Studio component: DroneWBox
                // WARNING: EntryoadPath is not connected to a robot.
                droneWBox_part48_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathEntryoadPath?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\DroneShipping\\DroneWithBox.png" : productionPathEntryoadPath.PartImagePath);
                var optionsEntryoadPath = new PathAnimationOptions
                {
                    Duration = TimeSpan.FromSeconds(2),
                    AutoStart = false,
                    RotateWithPath = false,
                    AutoReverse = false,
                    SpeedRatio = 1,
                    AccelerationRatio = 0,
                    DecelerationRatio = 0,
                    ZIndex = 2002,
                    InitialScale = .73,
                    ControlWidth = 100,
                    ControlHeight = 100
                };
                // Code for Layout Item: EntryoadPath
                var layoutItem48 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "EntryoadPath", StringComparison.OrdinalIgnoreCase))
                    ?? throw new InvalidOperationException($"Layout item 'EntryoadPath' was not found in location {_locationId}.");
                _pathHandlerEntryoadPath = GameAnimationHelper.AddControlOnPath("EntryoadPath", string.IsNullOrWhiteSpace(productionPathEntryoadPath?.PartName) ? "DroneWBox" : productionPathEntryoadPath.PartName, "", "", _view.MainCanvas,
                    droneWBox_part48_productUC, layoutItem48.ItemDataJson ?? string.Empty, optionsEntryoadPath);

                _productionSession.Add(_pathHandlerEntryoadPath);
                productionPaths.TryGetValue("RightProductStorePath", out var productionPathRightProductStorePath);
                // WARNING: RightProductStorePath has no dropped product assignment.
                // WARNING: RightProductStorePath is not connected to a robot.
                unassigned_part49_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathRightProductStorePath?.PartImagePath)
                    ? Imagehelper.GetImagePath(System.IO.Path.Combine(GlobalAllApps.ImageFolder, "Stores", "warehoouserollingrobot.png"))
                    : productionPathRightProductStorePath.PartImagePath);
                // Code for Layout Item: RightProductStorePath
                var layoutItem49 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "RightProductStorePath", StringComparison.OrdinalIgnoreCase))
                    ?? throw new InvalidOperationException($"Layout item 'RightProductStorePath' was not found in location {_locationId}.");
                _pathHandlerRightProductStorePath = GameAnimationHelper.AddControlOnPath("RightProductStorePath", string.IsNullOrWhiteSpace(productionPathRightProductStorePath?.PartName) ? "RightProductStorePathPart" : productionPathRightProductStorePath.PartName, "", "", _view.MainCanvas,
                    unassigned_part49_productUC, layoutItem49.ItemDataJson ?? string.Empty, options);

                _productionSession.Add(_pathHandlerRightProductStorePath);
                productionPaths.TryGetValue("LeftProductStorePath", out var productionPathLeftProductStorePath);
                // WARNING: LeftProductStorePath has no dropped product assignment.
                // WARNING: LeftProductStorePath is not connected to a robot.
                unassigned_part50_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathLeftProductStorePath?.PartImagePath)
                    ? Imagehelper.GetImagePath(System.IO.Path.Combine(GlobalAllApps.ImageFolder, "Stores", "warehoouserollingrobot.png"))
                    : productionPathLeftProductStorePath.PartImagePath);
                // Code for Layout Item: LeftProductStorePath
                var layoutItem50 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "LeftProductStorePath", StringComparison.OrdinalIgnoreCase))
                    ?? throw new InvalidOperationException($"Layout item 'LeftProductStorePath' was not found in location {_locationId}.");
                _pathHandlerLeftProductStorePath = GameAnimationHelper.AddControlOnPath("LeftProductStorePath", string.IsNullOrWhiteSpace(productionPathLeftProductStorePath?.PartName) ? "LeftProductStorePathPart" : productionPathLeftProductStorePath.PartName, "", "", _view.MainCanvas,
                    unassigned_part50_productUC, layoutItem50.ItemDataJson ?? string.Empty, options);

                _productionSession.Add(_pathHandlerLeftProductStorePath);
                foreach (var task in _robotTasks)
                    if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

    }
}
