// ============================================================
//  GENERATED BY CATORI.STUDIO.DEV
//
//  DO NOT FIX GENERATED CODE HERE.
//
//  If this code is incorrect, fix the generator in Studio
//  and regenerate this file.
// ============================================================
//  CODE GENERATION VERSION: 88

using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Objects.Hotspots;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.FactoryControls;
using CatoriUCLibrary.Views.Person;
using CatoriUCLibrary.Views.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Controls;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    // Generated by Catori.Studio.Dev, generation 88. Regenerate in Studio; do not edit by hand.
    [System.CodeDom.Compiler.GeneratedCode("Catori.Studio.Dev", "88")]
    public partial class BeachTravel3SubController : LocationSubControllerBase, ILocationSubController
    {
        public const long GeneratedCodeVersion = 88;

        partial void OnGeneratedLocationInitialized();
        partial void OnGeneratedProductionStarted();
        partial void OnGeneratedProductionStopping();
        partial void OnGeneratedAnimationCompleted(AnimationCompleteMessage message);

        // Generated code for location layout items
        FrameworkElement unassigned_part83_productUC;
        PathAnimationHandle _pathHandlerFlyingPath;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
        };
        private readonly PathAnimationSession _productionSession = new();

        private void SetupAnimations()
        {
            try
            {
        var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("BeachTravel3").GetAwaiter().GetResult()
            ?? throw new InvalidOperationException("Location 'BeachTravel3' was not found in the game database. Export the Studio location before running generated code.");
        _locationId = generatedLocation.LocationId;
        var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
        var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
        PathAnimationOptions ? options = new PathAnimationOptions();
        options.Duration = TimeSpan.FromSeconds(2);
        options.InitialScale = .73;
        options.AutoStart = false;
        PathAnimationOptions droneOptions = new PathAnimationOptions();
        droneOptions.Duration = TimeSpan.FromSeconds(2);
        droneOptions.InitialScale = .73;
        droneOptions.AutoStart = false;
        droneOptions.RotateWithPath = false;
        droneOptions.ControlWidth = 100;
        droneOptions.ControlHeight = 100;
        productionPaths.TryGetValue("FlyingPath", out var productionPathFlyingPath);
        // WARNING: FlyingPath has no dropped product assignment.
        // WARNING: FlyingPath is not connected to a robot.
        unassigned_part83_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathFlyingPath?.PartImagePath) ? "" : productionPathFlyingPath.PartImagePath);
        var optionsFlyingPath = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(4), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = false, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73, Completed = control => { if (control is CatoriUCLibrary.Views.Airplane.AirplaneUC airplane) _ = airplane.SetLandingGearAsync(true, TimeSpan.FromMilliseconds(650)); }, ControlWidth = 100, ControlHeight = 100
        };
        // Code for Layout Item: FlyingPath
        var layoutItem83 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "FlyingPath", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 83)
            ?? throw new InvalidOperationException($"Layout item 'FlyingPath' was not found in location {_locationId}.");
        _pathHandlerFlyingPath = GameAnimationHelper.AddControlOnPath("FlyingPath", string.IsNullOrWhiteSpace(productionPathFlyingPath?.PartName) ? "FlyingPathPart" : productionPathFlyingPath.PartName, "BeachAirport", "TransitionToView", _view.MainCanvas,
            unassigned_part83_productUC, layoutItem83.ItemDataJson ?? string.Empty, optionsFlyingPath);

        _productionSession.Add(_pathHandlerFlyingPath);
        _productionSession.AddDeferredPath("FlyingPath");
        foreach (var task in _robotTasks)
            if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                case ProductionAction.StartPath:
                    // PathAnimationSession starts the configured target with its assigned control.
                    break;
                case ProductionAction.TransitionToView:
                    _ = TransitionToLocationViewAsync(message.TargetName);
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
            OnGeneratedAnimationCompleted(message);
        }
        // Call SetupPeople(); before SetupFactoryControlPanels().

        private void SetupPeople()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }
        // No factory control panels are configured for this location.
        // No people are configured for this location.

        public BeachTravel3SubController(Location_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            InitializeLocationFeature("static airplanes", SetupStaticAirplanes);
            InitializeLocationFeature("people", SetupPeople);
            InitializeLocationFeature("factory control panels", SetupFactoryControlPanels);
            InitializeLocationFeature("path animations", SetupAnimations);
            InitializeLocationFeature("hotspots", () =>
                HotspotLayer.Attach(_view.MainCanvas, LoadLayoutItemsNow(), _view, _productionSession.StartPath));
            OnGeneratedLocationInitialized();
        }

        public void StartProduction()
        {
        var robotConfigurations = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetRobots(_locationId);
        foreach (var configuration in robotConfigurations)
        {
            var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
            if (robot == null) continue;
            robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
            robot.OutputPartImagePath = configuration.OutputPartImagePath;
        }
        _productionSession.StartRoots();
        OnGeneratedProductionStarted();
        }

        public void StopProduction()
        {
            OnGeneratedProductionStopping();
            _productionSession.StopAll();
        }

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
