// ============================================================
//  GENERATED BY CATORI.STUDIO.DEV
//
//  DO NOT FIX GENERATED CODE HERE.
//
//  If this code is incorrect, fix the generator in Studio
//  and regenerate this file.
// ============================================================
//  CODE GENERATION VERSION: 89

using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Objects.Hotspots;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.FactoryControls;
using CatoriUCLibrary.Views.Person;
using CatoriUCLibrary.Views.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Controls;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    // Generated by Catori.Studio.Dev, generation 89. Regenerate in Studio; do not edit by hand.
    [System.CodeDom.Compiler.GeneratedCode("Catori.Studio.Dev", "89")]
    public partial class Factory1SubController : LocationSubControllerBase, ILocationSubController
    {
        public const long GeneratedCodeVersion = 89;

        partial void OnGeneratedLocationInitialized();
        partial void OnGeneratedProductionStarted();
        partial void OnGeneratedProductionStopping();
        partial void OnGeneratedAnimationCompleted(AnimationCompleteMessage message);

        // Generated code for location layout items
        FrameworkElement paintBrush3_part36_productUC;
        PathAnimationHandle _pathHandlerC1Run;
        FrameworkElement paintBottles3_part37_productUC;
        PathAnimationHandle _pathHandlerCMiddlerun;
        FrameworkElement unassigned_part38_productUC;
        PathAnimationHandle _pathHandlerC3Run;
        FrameworkElement dromeSawbox_part41_productUC;
        PathAnimationHandle _pathHandlerDroneDelivery;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
            new("RobotLeft", "C1Run", "CMiddlerun", new double[][] { new double[] { -58.72809505462956, -25.103841290654287, -102.01489248639456, -55.08565261666365 }, new double[] { -124.56274942625913, 65.09192997496959, 94.43199200284425, 35.443819289446424 }, new double[] { -87.27203026241429, -27.004089007994395, -39.61504212059501, -85.30292532321792 } }),
            new("RobotRight", "CMiddlerun", "C3Run", new double[][] { new double[] { -74.97809034828738, -63.05141378432397, -61.29499194794323, -133.0421483854298 }, new double[] { -114.71604412345327, 61.43665511052206, 70.53760840850805, 59.309642578458124 }, new double[] { -113.87614856783841, -21.08303939523151, -57.89630966742436, -39.45682122292851 }, new double[] { -57.48926324494612, 49.24789175524168, -10.604129848215791, 106.45953790938381 } }),
        };
        private readonly PathAnimationSession _productionSession = new();

        private void SetupAnimations()
        {
            try
            {
        var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("Factory1").GetAwaiter().GetResult()
            ?? throw new InvalidOperationException("Location 'Factory1' was not found in the game database. Export the Studio location before running generated code.");
        _locationId = generatedLocation.LocationId;
        var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
        var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
        PathAnimationOptions ? options = new PathAnimationOptions();
        options.Duration = TimeSpan.FromSeconds(2);
        options.InitialScale = .73;
        options.AutoStart = false;
        PathAnimationOptions droneOptions = new PathAnimationOptions();
        droneOptions.Duration = TimeSpan.FromSeconds(2);
        droneOptions.InitialScale = .73;
        droneOptions.AutoStart = false;
        droneOptions.RotateWithPath = false;
        droneOptions.ControlWidth = 100;
        droneOptions.ControlHeight = 100;
        productionPaths.TryGetValue("C1Run", out var productionPathC1Run);
        // Assigned product: PaintBrush3 (PartId 10)
        paintBrush3_part36_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathC1Run?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Factories\\PaintBrush.png" : productionPathC1Run.PartImagePath);
        // Code for Layout Item: C1Run
        var layoutItem36 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "C1Run", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 36)
            ?? throw new InvalidOperationException($"Layout item 'C1Run' was not found in location {_locationId}.");
        _pathHandlerC1Run = GameAnimationHelper.AddControlOnPath("C1Run", string.IsNullOrWhiteSpace(productionPathC1Run?.PartName) ? "PaintBrush3" : productionPathC1Run.PartName, "RobotLeft", "Pickup", _view.MainCanvas,
            paintBrush3_part36_productUC, layoutItem36.ItemDataJson ?? string.Empty, options);

        _productionSession.Add(_pathHandlerC1Run);
        productionPaths.TryGetValue("CMiddlerun", out var productionPathCMiddlerun);
        // Assigned product: PaintBottles3 (PartId 11)
        paintBottles3_part37_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathCMiddlerun?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Factories\\PaintBottles.png" : productionPathCMiddlerun.PartImagePath);
        // Code for Layout Item: CMiddlerun
        var layoutItem37 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "CMiddlerun", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 37)
            ?? throw new InvalidOperationException($"Layout item 'CMiddlerun' was not found in location {_locationId}.");
        _pathHandlerCMiddlerun = GameAnimationHelper.AddControlOnPath("CMiddlerun", string.IsNullOrWhiteSpace(productionPathCMiddlerun?.PartName) ? "PaintBottles3" : productionPathCMiddlerun.PartName, "RobotRight", "Pickup", _view.MainCanvas,
            paintBottles3_part37_productUC, layoutItem37.ItemDataJson ?? string.Empty, options);

        _productionSession.Add(_pathHandlerCMiddlerun);
        productionPaths.TryGetValue("C3Run", out var productionPathC3Run);
        // WARNING: C3Run has no dropped product assignment.
        // C3Run is fed by a robot and has no outgoing pickup robot.
        unassigned_part38_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathC3Run?.PartImagePath) ? "" : productionPathC3Run.PartImagePath);
        var optionsC3Run = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = true, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73
        };
        // Code for Layout Item: C3Run
        var layoutItem38 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "C3Run", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 38)
            ?? throw new InvalidOperationException($"Layout item 'C3Run' was not found in location {_locationId}.");
        _pathHandlerC3Run = GameAnimationHelper.AddControlOnPath("C3Run", string.IsNullOrWhiteSpace(productionPathC3Run?.PartName) ? "C3RunPart" : productionPathC3Run.PartName, "DroneDelivery", "DronePickup", _view.MainCanvas,
            unassigned_part38_productUC, layoutItem38.ItemDataJson ?? string.Empty, optionsC3Run);

        _productionSession.Add(_pathHandlerC3Run);
        _productionSession.AddDeferredPath("C3Run");
        productionPaths.TryGetValue("DroneDelivery", out var productionPathDroneDelivery);
        // Assigned product: DromeSawbox (PartId 9)
        // WARNING: DroneDelivery is not connected to a robot.
        dromeSawbox_part41_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathDroneDelivery?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\DroneShipping\\DroneWIthSawBox.png" : productionPathDroneDelivery.PartImagePath);
        var optionsDroneDelivery = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = true, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73
        };
        // Code for Layout Item: DroneDelivery
        var layoutItem41 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "DroneDelivery", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 41)
            ?? throw new InvalidOperationException($"Layout item 'DroneDelivery' was not found in location {_locationId}.");
        _pathHandlerDroneDelivery = GameAnimationHelper.AddControlOnPath("DroneDelivery", string.IsNullOrWhiteSpace(productionPathDroneDelivery?.PartName) ? "DromeSawbox" : productionPathDroneDelivery.PartName, "", "", _view.MainCanvas,
            dromeSawbox_part41_productUC, layoutItem41.ItemDataJson ?? string.Empty, optionsDroneDelivery);

        _productionSession.Add(_pathHandlerDroneDelivery);
        foreach (var task in _robotTasks)
            if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    if (string.Equals(message.TargetName, "DroneDelivery", StringComparison.OrdinalIgnoreCase)) _pathHandlerDroneDelivery.Start();
                    break;
                case ProductionAction.StartPath:
                    // PathAnimationSession starts the configured target with its assigned control.
                    break;
                case ProductionAction.TransitionToView:
                    _ = TransitionToLocationViewAsync(message.TargetName);
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
            OnGeneratedAnimationCompleted(message);
        }
        // Call SetupPeople(); before SetupFactoryControlPanels().

        private void SetupPeople()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }
        // No factory control panels are configured for this location.
        // No people are configured for this location.

        public Factory1SubController(Location_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            InitializeLocationFeature("static airplanes", SetupStaticAirplanes);
            InitializeLocationFeature("people", SetupPeople);
            InitializeLocationFeature("factory control panels", SetupFactoryControlPanels);
            InitializeLocationFeature("path animations", SetupAnimations);
            InitializeLocationFeature("hotspots", () =>
                HotspotLayer.Attach(_view.MainCanvas, LoadLayoutItemsNow(), _view, _productionSession.StartPath));
            OnGeneratedLocationInitialized();
        }

        public void StartProduction()
        {
        var robotConfigurations = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetRobots(_locationId);
        foreach (var configuration in robotConfigurations)
        {
            var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
            if (robot == null) continue;
            robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
            robot.OutputPartImagePath = configuration.OutputPartImagePath;
        }
        _productionSession.StartRoots();
        OnGeneratedProductionStarted();
        }

        public void StopProduction()
        {
            OnGeneratedProductionStopping();
            _productionSession.StopAll();
        }

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
