// ============================================================
//  GENERATED BY CATORI.STUDIO.DEV
//
//  DO NOT FIX GENERATED CODE HERE.
//
//  If this code is incorrect, fix the generator in Studio
//  and regenerate this file.
// ============================================================
//  CODE GENERATION VERSION: 95

using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Objects.Hotspots;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.FactoryControls;
using CatoriUCLibrary.Views.Person;
using CatoriUCLibrary.Views.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Controls;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    // Generated by Catori.Studio.Dev, generation 95. Regenerate in Studio; do not edit by hand.
    [System.CodeDom.Compiler.GeneratedCode("Catori.Studio.Dev", "95")]
    public partial class factory6SubController : LocationSubControllerBase, ILocationSubController
    {
        public const long GeneratedCodeVersion = 95;

        partial void OnGeneratedLocationInitialized();
        partial void OnGeneratedProductionStarted();
        partial void OnGeneratedProductionStopping();
        partial void OnGeneratedAnimationCompleted(AnimationCompleteMessage message);

        // Generated code for location layout items
        FrameworkElement partA_part57_productUC;
        PathAnimationHandle _pathHandlerConveyorMiddleLeft;
        FrameworkElement robotRolling_part58_productUC;
        PathAnimationHandle _pathHandlerRObotRolling1;
        FrameworkElement drone_part61_productUC;
        PathAnimationHandle _pathHandlerRollingRobot;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
        };
        private readonly PathAnimationSession _productionSession = new();

        private void SetupAnimations()
        {
            try
            {
        var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("factory6").GetAwaiter().GetResult()
            ?? throw new InvalidOperationException("Location 'factory6' was not found in the game database. Export the Studio location before running generated code.");
        _locationId = generatedLocation.LocationId;
        var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
        var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
        PathAnimationOptions ? options = new PathAnimationOptions();
        options.Duration = TimeSpan.FromSeconds(2);
        options.InitialScale = .73;
        options.AutoStart = false;
        PathAnimationOptions droneOptions = new PathAnimationOptions();
        droneOptions.Duration = TimeSpan.FromSeconds(2);
        droneOptions.InitialScale = .73;
        droneOptions.AutoStart = false;
        droneOptions.RotateWithPath = false;
        droneOptions.ControlWidth = 100;
        droneOptions.ControlHeight = 100;
        productionPaths.TryGetValue("ConveyorMiddleLeft", out var productionPathConveyorMiddleLeft);
        // Assigned product: PartA (PartId 5)
        // WARNING: ConveyorMiddleLeft is not connected to a robot.
        partA_part57_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathConveyorMiddleLeft?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Factories\\PartA1.png" : productionPathConveyorMiddleLeft.PartImagePath);
        // Code for Layout Item: ConveyorMiddleLeft
        var layoutItem57 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "ConveyorMiddleLeft", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 57)
            ?? throw new InvalidOperationException($"Layout item 'ConveyorMiddleLeft' was not found in location {_locationId}.");
        _pathHandlerConveyorMiddleLeft = GameAnimationHelper.AddControlOnPath("ConveyorMiddleLeft", string.IsNullOrWhiteSpace(productionPathConveyorMiddleLeft?.PartName) ? "PartA" : productionPathConveyorMiddleLeft.PartName, "", "", _view.MainCanvas,
            partA_part57_productUC, layoutItem57.ItemDataJson ?? string.Empty, options);

        _productionSession.Add(_pathHandlerConveyorMiddleLeft);
        productionPaths.TryGetValue("RObotRolling1", out var productionPathRObotRolling1);
        // Assigned Studio component: RobotRolling
        // WARNING: RObotRolling1 is not connected to a robot.
        robotRolling_part58_productUC = CatoriUCLibrary.Views.VisualParts.VisualObjectControlFactory.Create("Image", "") ?? new ProductUC(string.IsNullOrWhiteSpace(productionPathRObotRolling1?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Stores\\warehoouserollingrobot.png" : productionPathRObotRolling1.PartImagePath);
        var optionsRObotRolling1 = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = true, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73, ControlWidth = 100, ControlHeight = 100
        };
        // Code for Layout Item: RObotRolling1
        var layoutItem58 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "RObotRolling1", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 58)
            ?? throw new InvalidOperationException($"Layout item 'RObotRolling1' was not found in location {_locationId}.");
        _pathHandlerRObotRolling1 = GameAnimationHelper.AddControlOnPath("RObotRolling1", string.IsNullOrWhiteSpace(productionPathRObotRolling1?.PartName) ? "RobotRolling" : productionPathRObotRolling1.PartName, "", "", _view.MainCanvas,
            robotRolling_part58_productUC, layoutItem58.ItemDataJson ?? string.Empty, optionsRObotRolling1);

        _productionSession.Add(_pathHandlerRObotRolling1);
        productionPaths.TryGetValue("RollingRobot", out var productionPathRollingRobot);
        // Assigned Studio component: Drone
        // WARNING: RollingRobot is not connected to a robot.
        drone_part61_productUC = CatoriUCLibrary.Views.VisualParts.VisualObjectControlFactory.Create("Image", "") ?? new ProductUC(string.IsNullOrWhiteSpace(productionPathRollingRobot?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\DroneShipping\\DoneEmpty.png" : productionPathRollingRobot.PartImagePath);
        var optionsRollingRobot = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = true, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73, ControlWidth = 100, ControlHeight = 100
        };
        // Code for Layout Item: RollingRobot
        var layoutItem61 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "RollingRobot", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 61)
            ?? throw new InvalidOperationException($"Layout item 'RollingRobot' was not found in location {_locationId}.");
        _pathHandlerRollingRobot = GameAnimationHelper.AddControlOnPath("RollingRobot", string.IsNullOrWhiteSpace(productionPathRollingRobot?.PartName) ? "Drone" : productionPathRollingRobot.PartName, "", "", _view.MainCanvas,
            drone_part61_productUC, layoutItem61.ItemDataJson ?? string.Empty, optionsRollingRobot);

        _productionSession.Add(_pathHandlerRollingRobot);
        foreach (var task in _robotTasks)
            if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                case ProductionAction.StartPath:
                    // PathAnimationSession starts the configured target with its assigned control.
                    break;
                case ProductionAction.TransitionToView:
                    _ = TransitionToLocationViewAsync(message.TargetName);
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
            OnGeneratedAnimationCompleted(message);
        }
        // Call SetupPeople(); before SetupFactoryControlPanels().
        private PersonUC? _personActive;
        private FactoryControlPanelUC? _factoryPanel;

        private void SetupPeople()
        {
            try
            {
                _personActive = _view.MainCanvas.Children.OfType<PersonUC>().FirstOrDefault(person =>
                    string.Equals(person.ToolTip as string, "PersonActive", StringComparison.OrdinalIgnoreCase))
                    ?? CatoriApp.Core.Objects.Shared.GlobalAllApps.GetPerson(new CatoriApp.Core.Objects.Shared.PersonMetadata(
                        "PersonActive",
                        300,
                        400,
                        PersonActivity.Idle,
                        true,
                        true,
                        "",
                        PersonRole.Avatar));
                _personActive.ToolTip = "PersonActive";
                Canvas.SetLeft(_personActive, 810);
                Canvas.SetTop(_personActive, 500);
                Panel.SetZIndex(_personActive, 2200);
                if (_personActive.Parent == null)
                {
                    _view.MainCanvas.Children.Add(_personActive);
                }

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
                _factoryPanel = new FactoryControlPanelUC
                {
                    Name = "FactoryPanel",
                    Width = 150,
                    Height = 180,
                    Mode = FactoryControlPanelMode.Lever,
                    AnimationTargetName = "",
                    ActivationRadius = 65,
                    IsDragEnabled = false,
                    TargetPerson = _personActive
                };
                Canvas.SetLeft(_factoryPanel, 1734.928755956515);
                Canvas.SetTop(_factoryPanel, 42.18165905784011);
                Panel.SetZIndex(_factoryPanel, 2200);
                _view.MainCanvas.Children.Add(_factoryPanel);

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }

        public factory6SubController(Location_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            InitializeLocationFeature("static airplanes", SetupStaticAirplanes);
            InitializeLocationFeature("people", SetupPeople);
            InitializeLocationFeature("factory control panels", SetupFactoryControlPanels);
            InitializeLocationFeature("path animations", SetupAnimations);
            InitializeLocationFeature("hotspots", () =>
                HotspotLayer.Attach(_view.MainCanvas, LoadLayoutItemsNow(), _view, _productionSession.StartPath));
            OnGeneratedLocationInitialized();
        }

        public void StartProduction()
        {
        var robotConfigurations = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetRobots(_locationId);
        foreach (var configuration in robotConfigurations)
        {
            var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
            if (robot == null) continue;
            robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
            robot.OutputPartImagePath = configuration.OutputPartImagePath;
        }
        _productionSession.StartRoots();
        OnGeneratedProductionStarted();
        }

        public void StopProduction()
        {
            OnGeneratedProductionStopping();
            _productionSession.StopAll();
        }

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
