// ============================================================
//  GENERATED BY CATORI.STUDIO.DEV
//
//  DO NOT FIX GENERATED CODE HERE.
//
//  If this code is incorrect, fix the generator in Studio
//  and regenerate this file.
// ============================================================
//  CODE GENERATION VERSION: 90

using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Objects.Hotspots;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.FactoryControls;
using CatoriUCLibrary.Views.Person;
using CatoriUCLibrary.Views.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Controls;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    // Generated by Catori.Studio.Dev, generation 90. Regenerate in Studio; do not edit by hand.
    [System.CodeDom.Compiler.GeneratedCode("Catori.Studio.Dev", "90")]
    public partial class Factory3SubController : LocationSubControllerBase, ILocationSubController
    {
        public const long GeneratedCodeVersion = 90;

        partial void OnGeneratedLocationInitialized();
        partial void OnGeneratedProductionStarted();
        partial void OnGeneratedProductionStopping();
        partial void OnGeneratedAnimationCompleted(AnimationCompleteMessage message);

        // Generated code for location layout items
        FrameworkElement paintBottles3_part42_productUC;
        PathAnimationHandle _pathHandlerCrunLeft;
        FrameworkElement unassigned_part43_productUC;
        PathAnimationHandle _pathHandlerCMidL;
        FrameworkElement paintBrush3_part44_productUC;
        PathAnimationHandle _pathHandlerCMidR;
        FrameworkElement unassigned_part45_productUC;
        PathAnimationHandle _pathHandlerCRunR;
        FrameworkElement robotMover_part46_productUC;
        PathAnimationHandle _pathHandlerRobotMover;
        FrameworkElement unassigned_part47_productUC;
        PathAnimationHandle _pathHandlerDroneDelivery;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
            new("robot3", "CMidR", "CRunR", new double[][] { new double[] { -91.11800470631697, -43.338758637068636, -34.37373031113009, -58.719134703240684 }, new double[] { -91.11800470631697, 6.791363719396102, 84.18532594995325, 85.88451416263985 } }),
            new("Robot4", "CrunLeft", "CMidL", new double[][] { new double[] { -91.88889517556389, -11.12203130566543, -72.40703300560097, -79.93653608968589 }, new double[] { -91.88889517556389, 19.199322287154843, 75.23011806972988, 35.26449746768071 }, new double[] { -90, -33.167144432317556, -63.98301685236886, -52.88664398024707 }, new double[] { -90, 24.198145868930126, 54.44446998585924, 79.65799313660625 } }),
            new("robot4", "CMidL", "CMidR", new double[][] { new double[] { -107.27355679236746, -27.15909616409084, -28.43093716108345, -24.03308921466254 }, new double[] { -59.69414654351782, 2.000185939147322, 48.24532355995729, 12.37407464033322 } }),
        };
        private readonly PathAnimationSession _productionSession = new();

        private void SetupAnimations()
        {
            try
            {
        var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("Factory3").GetAwaiter().GetResult()
            ?? throw new InvalidOperationException("Location 'Factory3' was not found in the game database. Export the Studio location before running generated code.");
        _locationId = generatedLocation.LocationId;
        var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
        var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
        PathAnimationOptions ? options = new PathAnimationOptions();
        options.Duration = TimeSpan.FromSeconds(2);
        options.InitialScale = .73;
        options.AutoStart = false;
        PathAnimationOptions droneOptions = new PathAnimationOptions();
        droneOptions.Duration = TimeSpan.FromSeconds(2);
        droneOptions.InitialScale = .73;
        droneOptions.AutoStart = false;
        droneOptions.RotateWithPath = false;
        droneOptions.ControlWidth = 100;
        droneOptions.ControlHeight = 100;
        productionPaths.TryGetValue("CrunLeft", out var productionPathCrunLeft);
        // Assigned product: PaintBottles3 (PartId 11)
        paintBottles3_part42_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathCrunLeft?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Factories\\PaintBottles.png" : productionPathCrunLeft.PartImagePath);
        var optionsCrunLeft = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = true, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73
        };
        // Code for Layout Item: CrunLeft
        var layoutItem42 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "CrunLeft", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 42)
            ?? throw new InvalidOperationException($"Layout item 'CrunLeft' was not found in location {_locationId}.");
        _pathHandlerCrunLeft = GameAnimationHelper.AddControlOnPath("CrunLeft", string.IsNullOrWhiteSpace(productionPathCrunLeft?.PartName) ? "PaintBottles3" : productionPathCrunLeft.PartName, "Robot4", "Pickup", _view.MainCanvas,
            paintBottles3_part42_productUC, layoutItem42.ItemDataJson ?? string.Empty, optionsCrunLeft);

        _productionSession.Add(_pathHandlerCrunLeft);
        _productionSession.AddDeferredPath("CrunLeft");
        productionPaths.TryGetValue("CMidL", out var productionPathCMidL);
        // WARNING: CMidL has no dropped product assignment.
        unassigned_part43_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathCMidL?.PartImagePath) ? "" : productionPathCMidL.PartImagePath);
        // Code for Layout Item: CMidL
        var layoutItem43 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "CMidL", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 43)
            ?? throw new InvalidOperationException($"Layout item 'CMidL' was not found in location {_locationId}.");
        _pathHandlerCMidL = GameAnimationHelper.AddControlOnPath("CMidL", string.IsNullOrWhiteSpace(productionPathCMidL?.PartName) ? "CMidLPart" : productionPathCMidL.PartName, "robot4", "Pickup", _view.MainCanvas,
            unassigned_part43_productUC, layoutItem43.ItemDataJson ?? string.Empty, options);

        _productionSession.Add(_pathHandlerCMidL);
        productionPaths.TryGetValue("CMidR", out var productionPathCMidR);
        // Assigned product: PaintBrush3 (PartId 10)
        paintBrush3_part44_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathCMidR?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Factories\\PaintBrush.png" : productionPathCMidR.PartImagePath);
        // Code for Layout Item: CMidR
        var layoutItem44 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "CMidR", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 44)
            ?? throw new InvalidOperationException($"Layout item 'CMidR' was not found in location {_locationId}.");
        _pathHandlerCMidR = GameAnimationHelper.AddControlOnPath("CMidR", string.IsNullOrWhiteSpace(productionPathCMidR?.PartName) ? "PaintBrush3" : productionPathCMidR.PartName, "robot3", "Pickup", _view.MainCanvas,
            paintBrush3_part44_productUC, layoutItem44.ItemDataJson ?? string.Empty, options);

        _productionSession.Add(_pathHandlerCMidR);
        productionPaths.TryGetValue("CRunR", out var productionPathCRunR);
        // WARNING: CRunR has no dropped product assignment.
        // CRunR is fed by a robot and has no outgoing pickup robot.
        unassigned_part45_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathCRunR?.PartImagePath) ? "" : productionPathCRunR.PartImagePath);
        var optionsCRunR = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = true, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73
        };
        // Code for Layout Item: CRunR
        var layoutItem45 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "CRunR", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 45)
            ?? throw new InvalidOperationException($"Layout item 'CRunR' was not found in location {_locationId}.");
        _pathHandlerCRunR = GameAnimationHelper.AddControlOnPath("CRunR", string.IsNullOrWhiteSpace(productionPathCRunR?.PartName) ? "CRunRPart" : productionPathCRunR.PartName, "DroneDelivery", "StartPath", _view.MainCanvas,
            unassigned_part45_productUC, layoutItem45.ItemDataJson ?? string.Empty, optionsCRunR);

        _productionSession.Add(_pathHandlerCRunR);
        _productionSession.AddDeferredPath("CRunR");
        productionPaths.TryGetValue("RobotMover", out var productionPathRobotMover);
        // Assigned product: RobotMover (PartId 16)
        // WARNING: RobotMover is not connected to a robot.
        robotMover_part46_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathRobotMover?.PartImagePath) ? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Stores\\warehoouserollingrobot.png" : productionPathRobotMover.PartImagePath);
        var optionsRobotMover = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = true, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73
        };
        // Code for Layout Item: RobotMover
        var layoutItem46 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "RobotMover", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 46)
            ?? throw new InvalidOperationException($"Layout item 'RobotMover' was not found in location {_locationId}.");
        _pathHandlerRobotMover = GameAnimationHelper.AddControlOnPath("RobotMover", string.IsNullOrWhiteSpace(productionPathRobotMover?.PartName) ? "RobotMover" : productionPathRobotMover.PartName, "CrunLeft", "StartPath", _view.MainCanvas,
            robotMover_part46_productUC, layoutItem46.ItemDataJson ?? string.Empty, optionsRobotMover);

        _productionSession.Add(_pathHandlerRobotMover);
        productionPaths.TryGetValue("DroneDelivery", out var productionPathDroneDelivery);
        // WARNING: DroneDelivery has no dropped product assignment.
        // WARNING: DroneDelivery is not connected to a robot.
        unassigned_part47_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathDroneDelivery?.PartImagePath) ? "" : productionPathDroneDelivery.PartImagePath);
        var optionsDroneDelivery = new PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = false, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = .73, ControlWidth = 100, ControlHeight = 100
        };
        // Code for Layout Item: DroneDelivery
        var layoutItem47 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "DroneDelivery", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 47)
            ?? throw new InvalidOperationException($"Layout item 'DroneDelivery' was not found in location {_locationId}.");
        _pathHandlerDroneDelivery = GameAnimationHelper.AddControlOnPath("DroneDelivery", string.IsNullOrWhiteSpace(productionPathDroneDelivery?.PartName) ? "DroneDeliveryPart" : productionPathDroneDelivery.PartName, "", "", _view.MainCanvas,
            unassigned_part47_productUC, layoutItem47.ItemDataJson ?? string.Empty, optionsDroneDelivery);

        _productionSession.Add(_pathHandlerDroneDelivery);
        _productionSession.AddDeferredPath("DroneDelivery");
        _productionSession.AddPathHandoff("CRunR", "DroneDelivery", TimeSpan.FromSeconds(0));
        _productionSession.AddPathHandoff("RobotMover", "CrunLeft", TimeSpan.FromSeconds(0));
        foreach (var task in _robotTasks)
            if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                case ProductionAction.StartPath:
                    // PathAnimationSession starts the configured target with its assigned control.
                    break;
                case ProductionAction.TransitionToView:
                    _ = TransitionToLocationViewAsync(message.TargetName);
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
            OnGeneratedAnimationCompleted(message);
        }
        // Call SetupPeople(); before SetupFactoryControlPanels().
        private PersonUC? _personActive;
        private FactoryControlPanelUC? _factoryPanel;

        private void SetupPeople()
        {
            try
            {
                _personActive = _view.MainCanvas.Children.OfType<PersonUC>().FirstOrDefault(person =>
                    string.Equals(person.ToolTip as string, "PersonActive", StringComparison.OrdinalIgnoreCase))
                    ?? CatoriApp.Core.Objects.Shared.GlobalAllApps.GetPerson(new CatoriApp.Core.Objects.Shared.PersonMetadata(
                        "PersonActive",
                        128.89990089197227,
                        171.86653452262965,
                        PersonActivity.Idle,
                        true,
                        true,
                        "",
                        PersonRole.Avatar));
                _personActive.ToolTip = "PersonActive";
                Canvas.SetLeft(_personActive, 1533.2738486647982);
                Canvas.SetTop(_personActive, 312.9763984479716);
                Panel.SetZIndex(_personActive, 2200);
                if (_personActive.Parent == null)
                {
                    _view.MainCanvas.Children.Add(_personActive);
                }

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
                _factoryPanel = new FactoryControlPanelUC
                {
                    Name = "FactoryPanel",
                    Width = 118.9593657086225,
                    Height = 142.751238850347,
                    Mode = FactoryControlPanelMode.Lever,
                    AnimationTargetName = "",
                    ActivationRadius = 65,
                    IsDragEnabled = false,
                    TargetPerson = _personActive
                };
                Canvas.SetLeft(_factoryPanel, 1760.8835066003114);
                Canvas.SetTop(_factoryPanel, 376.9985926631572);
                Panel.SetZIndex(_factoryPanel, 2200);
                _view.MainCanvas.Children.Add(_factoryPanel);

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }

        public Factory3SubController(Location_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            InitializeLocationFeature("static airplanes", SetupStaticAirplanes);
            InitializeLocationFeature("people", SetupPeople);
            InitializeLocationFeature("factory control panels", SetupFactoryControlPanels);
            InitializeLocationFeature("path animations", SetupAnimations);
            InitializeLocationFeature("hotspots", () =>
                HotspotLayer.Attach(_view.MainCanvas, LoadLayoutItemsNow(), _view, _productionSession.StartPath));
            OnGeneratedLocationInitialized();
        }

        public void StartProduction()
        {
        var robotConfigurations = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetRobots(_locationId);
        foreach (var configuration in robotConfigurations)
        {
            var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
            if (robot == null) continue;
            robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
            robot.OutputPartImagePath = configuration.OutputPartImagePath;
        }
        _productionSession.StartRoots();
        OnGeneratedProductionStarted();
        }

        public void StopProduction()
        {
            OnGeneratedProductionStopping();
            _productionSession.StopAll();
        }

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
