using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.ViewModels.Locations;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.FactoryControls;
using CatoriUCLibrary.Views.Person;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    public partial class Locationinterior3SubController : LocationSubControllerBase, ILocationSubController
    {
       
        // ============================================================
        //  GENERATED BY CATORI.STUDIO.DEV
        //
        //  DO NOT FIX GENERATED CODE HERE.
        //
        //  If this code is incorrect, fix the generator in Studio
        //  and regenerate this file.
        // ============================================================
        // Call SetupFactoryPeople(); before SetupFactoryControlPanels().
        private PersonUC? _personActive;
        private FactoryControlPanelUC? _factoryPanel;
        partial void OnConstructorCalled();
        private void SetupFactoryPeople()
        {
            try
            {
                _personActive = new PersonUC
                {
                    Name = "PersonActive",
                    Width = 128.89990089197227,
                    Height = 171.86653452262965,
                    CurrentActivity = PersonActivity.Idle,
                    IsDragEnabled = true,
                    IsArmEditingEnabled = true
                };
                Canvas.SetLeft(_personActive, 1533.2738486647982);
                Canvas.SetTop(_personActive, 312.9763984479716);
                Panel.SetZIndex(_personActive, 1224);
                _view.MainCanvas.Children.Add(_personActive);

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
                _factoryPanel = new FactoryControlPanelUC
                {
                    Name = "FactoryPanel",
                    Width = 118.9593657086225,
                    Height = 142.751238850347,
                    Mode = FactoryControlPanelMode.Lever,
                    AnimationTargetName = "",
                    ActivationRadius = 65,
                    IsDragEnabled = false,
                    TargetPerson = _personActive
                };
                Canvas.SetLeft(_factoryPanel, 1760.8835066003114);
                Canvas.SetTop(_factoryPanel, 376.9985926631572);
                Panel.SetZIndex(_factoryPanel, 1223);
                _view.MainCanvas.Children.Add(_factoryPanel);

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }

        public Locationinterior3SubController(FactoryInterior_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            OnConstructorCalled();
            SetupFactoryPeople();
            SetupFactoryControlPanels();
        }

        

        private LocationLayoutItemViewModel GetLayoutItem(
            IEnumerable<LocationLayoutItemViewModel> layoutItems, string itemName)
            => layoutItems.FirstOrDefault(item =>
                   string.Equals(item.ItemName, itemName, StringComparison.Ordinal))
               ?? throw new InvalidOperationException(
                   $"Layout item '{itemName}' was not found in Factory 3.");

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine(
                $"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
        }

        public void StartProduction()
        {
            ConfigureProductionRobots();
            _productionSession.StartRoots();
        }

        private void ConfigureProductionRobots()
        {
            foreach (var configuration in new ProductionLayoutRepository().GetRobots(_locationId))
            {
                var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                    string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
                if (robot == null) continue;
                robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
                robot.OutputPartImagePath = configuration.OutputPartImagePath;
            }
        }

        public void StopProduction() => _productionSession.StopAll();

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
