using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.RobotArm;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    public class LocationInterior1SubController : LocationSubControllerBase, 
        ILocationSubController
    {
        // Generated code for location layout items
       
        List<RobotPose> _robotPoses;
        FactoryInterior_UC _view;
        private bool _productionPrepared;
        public LocationInterior1SubController(FactoryInterior_UC view,long locationId) : base(locationId, view)
        {
            _view = view;
            //LoadLayoutItems();
            base._view = view;
            _locationId = locationId;
            SetupAnimations();
        }

        // ============================================================
        //  GENERATED BY CATORI.STUDIO.DEV
        //
        //  DO NOT FIX GENERATED CODE HERE.
        //
        //  If this code is incorrect, fix the generator in Studio
        //  and regenerate this file.
        // ============================================================
        // Generated code for location layout items
        ProductUC paintBrush3_part36_productUC;
        PathAnimationHandle _pathHandlerC1Run;
        ProductUC paintBottles3_part37_productUC;
        PathAnimationHandle _pathHandlerCMiddlerun;
        ProductUC unassigned_part38_productUC;
        PathAnimationHandle _pathHandlerC3Run;
        ProductUC dromeSawbox_part41_productUC;
        PathAnimationHandle _pathHandlerDroneDelivery;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
{
    new("RobotLeft", "C1Run", "CMiddlerun", new double[][] { new double[] { -58.72809505462956, -25.103841290654287, -102.01489248639456, -55.08565261666365 }, new double[] { -124.56274942625913, 65.09192997496959, 94.43199200284425, 35.443819289446424 }, new double[] { -87.27203026241429, -27.004089007994395, -39.61504212059501, -85.30292532321792 } }),
    new("RobotRight", "CMiddlerun", "C3Run", new double[][] { new double[] { -74.97809034828738, -63.05141378432397, -61.29499194794323, -133.0421483854298 }, new double[] { -114.71604412345327, 61.43665511052206, 70.53760840850805, 59.309642578458124 }, new double[] { -113.87614856783841, -21.08303939523151, -57.89630966742436, -39.45682122292851 }, new double[] { -57.48926324494612, 49.24789175524168, -10.604129848215791, 106.45953790938381 } }),
};
        private void SetupAnimations()
        {
            try
            {
                var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
                var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
                PathAnimationOptions? options = new PathAnimationOptions();
                options.Duration = TimeSpan.FromSeconds(2);
                options.InitialScale = .73;
                options.AutoStart = false;
                PathAnimationOptions droneOptions = new PathAnimationOptions();
                droneOptions.Duration = TimeSpan.FromSeconds(2);
                droneOptions.InitialScale = .73;
                droneOptions.AutoStart = false;
                droneOptions.RotateWithPath = false;
                droneOptions.ControlWidth = 100;
                droneOptions.ControlHeight = 100;
                productionPaths.TryGetValue("C1Run", out var productionPathC1Run);
                // Assigned product: PaintBrush3 (PartId 10)
                paintBrush3_part36_productUC = new ProductUC(productionPathC1Run?.PartImagePath ?? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Factories\\PaintBrush.png");
                // Code for Layout Item: C1Run
                var layoutItem36 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "C1Run", StringComparison.OrdinalIgnoreCase))
                    ?? throw new InvalidOperationException("Layout item 'C1Run' was not found in location 1.");
                _pathHandlerC1Run = GameAnimationHelper.AddControlOnPath("C1Run", productionPathC1Run?.PartName ?? "PaintBrush3", "RobotLeft", "Pickup", _view.MainCanvas,
                    paintBrush3_part36_productUC, layoutItem36.ItemDataJson ?? string.Empty, options);

                _productionSession.Add(_pathHandlerC1Run);
                productionPaths.TryGetValue("CMiddlerun", out var productionPathCMiddlerun);
                // Assigned product: PaintBottles3 (PartId 11)
                paintBottles3_part37_productUC = new ProductUC(productionPathCMiddlerun?.PartImagePath ?? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\Factories\\PaintBottles.png");
                // Code for Layout Item: CMiddlerun
                var layoutItem37 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "CMiddlerun", StringComparison.OrdinalIgnoreCase))
                    ?? throw new InvalidOperationException("Layout item 'CMiddlerun' was not found in location 1.");
                _pathHandlerCMiddlerun = GameAnimationHelper.AddControlOnPath("CMiddlerun", productionPathCMiddlerun?.PartName ?? "PaintBottles3", "RobotRight", "Pickup", _view.MainCanvas,
                    paintBottles3_part37_productUC, layoutItem37.ItemDataJson ?? string.Empty, options);

                _productionSession.Add(_pathHandlerCMiddlerun);
                productionPaths.TryGetValue("C3Run", out var productionPathC3Run);
                // WARNING: C3Run has no dropped product assignment.
                // C3Run is fed by a robot and has no outgoing pickup robot.
                unassigned_part38_productUC = new ProductUC(productionPathC3Run?.PartImagePath ?? "");
                var optionsC3Run = new PathAnimationOptions
                {
                    Duration = TimeSpan.FromSeconds(2),
                    AutoStart = false,
                    RotateWithPath = true,
                    AutoReverse = false,
                    SpeedRatio = 1,
                    AccelerationRatio = 0,
                    DecelerationRatio = 0,
                    ZIndex = 2002,
                    InitialScale = .73
                };
                // Code for Layout Item: C3Run
                var layoutItem38 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "C3Run", StringComparison.OrdinalIgnoreCase))
                    ?? throw new InvalidOperationException("Layout item 'C3Run' was not found in location 1.");
                _pathHandlerC3Run = GameAnimationHelper.AddControlOnPath("C3Run", productionPathC3Run?.PartName ?? "C3RunPart", "DroneDelivery", "DronePickup", _view.MainCanvas,
                    unassigned_part38_productUC, layoutItem38.ItemDataJson ?? string.Empty, optionsC3Run);

                _productionSession.Add(_pathHandlerC3Run);
                _productionSession.AddDeferredPath("C3Run");
                productionPaths.TryGetValue("DroneDelivery", out var productionPathDroneDelivery);
                // Assigned product: DromeSawbox (PartId 9)
                // WARNING: DroneDelivery is not connected to a robot.
                dromeSawbox_part41_productUC = new ProductUC(productionPathDroneDelivery?.PartImagePath ?? "C:\\Development\\Gaming\\Catori2026\\Catori_2026_v1\\Images\\DroneShipping\\DroneWIthSawBox.png");
                var optionsDroneDelivery = new PathAnimationOptions
                {
                    Duration = TimeSpan.FromSeconds(2),
                    AutoStart = false,
                    RotateWithPath = true,
                    AutoReverse = false,
                    SpeedRatio = 1,
                    AccelerationRatio = 0,
                    DecelerationRatio = 0,
                    ZIndex = 2002,
                    InitialScale = .73
                };
                // Code for Layout Item: DroneDelivery
                var layoutItem41 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "DroneDelivery", StringComparison.OrdinalIgnoreCase))
                    ?? throw new InvalidOperationException("Layout item 'DroneDelivery' was not found in location 1.");
                _pathHandlerDroneDelivery = GameAnimationHelper.AddControlOnPath("DroneDelivery", productionPathDroneDelivery?.PartName ?? "DromeSawbox", "", "", _view.MainCanvas,
                    dromeSawbox_part41_productUC, layoutItem41.ItemDataJson ?? string.Empty, optionsDroneDelivery);

                _productionSession.Add(_pathHandlerDroneDelivery);
                _productionSession.AddDeferredPath("DroneDelivery");
                foreach (var task in _robotTasks)
                    if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    if (string.Equals(message.TargetName, "DroneDelivery", StringComparison.OrdinalIgnoreCase)) _pathHandlerDroneDelivery.Start();
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
        }


        //private void SetupAnimations()
        //{
        //    try
        //    {
        //        var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
        //        var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
        //        PathAnimationOptions? options = new PathAnimationOptions();
        //        options.Duration = TimeSpan.FromSeconds(2);
        //        options.InitialScale = .73;
        //        options.AutoStart = false;
        //        productionPaths.TryGetValue("C1Run", out var productionPathC1Run);
        //        // Assigned product: PartA (PartId 5)
        //        partA_part36_productUC = new ProductUC(productionPathC1Run?.PartImagePath ?? string.Empty);
        //        // Code for Layout Item: C1Run
        //        var layoutItem36 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "C1Run", StringComparison.OrdinalIgnoreCase))
        //            ?? throw new InvalidOperationException("Layout item 'C1Run' was not found in location 1.");
        //        _pathHandlerC1Run = GameAnimationHelper.AddControlOnPath("C1Run", productionPathC1Run?.PartName ?? "PartA", "RobotLeft", "Pickup", _view.MainCanvas,
        //            partA_part36_productUC, layoutItem36.ItemDataJson ?? string.Empty, options);

        //        _productionSession.Add(_pathHandlerC1Run);
        //        productionPaths.TryGetValue("CMiddlerun", out var productionPathCMiddlerun);
        //        // Assigned product: PatB (PartId 6)
        //        patB_part37_productUC = new ProductUC(productionPathCMiddlerun?.PartImagePath ?? string.Empty);
        //        // Code for Layout Item: CMiddlerun
        //        var layoutItem37 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "CMiddlerun", StringComparison.OrdinalIgnoreCase))
        //            ?? throw new InvalidOperationException("Layout item 'CMiddlerun' was not found in location 1.");
        //        _pathHandlerCMiddlerun = GameAnimationHelper.AddControlOnPath("CMiddlerun", productionPathCMiddlerun?.PartName ?? "PatB", "RobotRight", "Pickup", _view.MainCanvas,
        //            patB_part37_productUC, layoutItem37.ItemDataJson ?? string.Empty, options);

        //        _productionSession.Add(_pathHandlerCMiddlerun);
        //        productionPaths.TryGetValue("C3Run", out var productionPathC3Run);
        //        // WARNING: C3Run has no dropped product assignment.
        //        // C3Run is fed by a robot and has no outgoing pickup robot.
        //        unassigned_part38_productUC = new ProductUC(productionPathC3Run?.PartImagePath ?? string.Empty);
        //        // Code for Layout Item: C3Run
        //        var layoutItem38 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "C3Run", StringComparison.OrdinalIgnoreCase))
        //            ?? throw new InvalidOperationException("Layout item 'C3Run' was not found in location 1.");
        //        _pathHandlerC3Run = GameAnimationHelper.AddControlOnPath("C3Run", productionPathC3Run?.PartName ?? "C3RunPart", "", "", _view.MainCanvas,
        //            unassigned_part38_productUC, layoutItem38.ItemDataJson ?? string.Empty, options);

        //        _productionSession.Add(_pathHandlerC3Run);
        //        productionPaths.TryGetValue("DroneDelivery", out var productionPathDroneDelivery);
        //        // WARNING: DroneDelivery has no dropped product assignment.
        //        // WARNING: DroneDelivery is not connected to a robot.
        //        unassigned_part41_productUC = new ProductUC(productionPathDroneDelivery?.PartImagePath ?? string.Empty);
        //        // Code for Layout Item: DroneDelivery
        //        var layoutItem41 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "DroneDelivery", StringComparison.OrdinalIgnoreCase))
        //            ?? throw new InvalidOperationException("Layout item 'DroneDelivery' was not found in location 1.");
        //        _pathHandlerDroneDelivery = GameAnimationHelper.AddControlOnPath("DroneDelivery", productionPathDroneDelivery?.PartName ?? "DroneDeliveryPart", "", "", _view.MainCanvas,
        //            unassigned_part41_productUC, layoutItem41.ItemDataJson ?? string.Empty, options);

        //        _productionSession.Add(_pathHandlerDroneDelivery);
        //        var robotConfigurations = new ProductionLayoutRepository().GetRobots(_locationId);
        //        foreach (var configuration in robotConfigurations)
        //        {
        //            var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
        //                string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.OrdinalIgnoreCase));
        //            if (robot == null)
        //                continue;

        //            robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
        //            robot.OutputPartImagePath = configuration.OutputPartImagePath;
        //        }
        //        foreach (var task in _robotTasks)
        //            if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);

        //    }
        //    catch (Exception ex)
        //    {

        //        throw;
        //    }       }




        public void OnAnimationCompleted()
        {
            System.Diagnostics.Debug.WriteLine("Animation Completed");

        }

        public void LoadPaths()
        {
            //PrepareProduction();
        }

        public void StartProduction()
        {
            System.Diagnostics.Debug.WriteLine("Start Production");
            ConfigureProductionRobots();
            _productionSession.StartRoots();
        }

        private void ConfigureProductionRobots()
        {
            var robotConfigurations = new ProductionLayoutRepository().GetRobots(_locationId);
            foreach (var configuration in robotConfigurations)
            {
                var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                    string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.OrdinalIgnoreCase));
                if (robot == null)
                    continue;

                robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
                robot.OutputPartImagePath = configuration.OutputPartImagePath;
            }
        }

        public void StopProduction()
        {
            System.Diagnostics.Debug.WriteLine("Stop Production");
            _productionSession.Clear();
            _productionPrepared=false;
        }

        private void PrepareProduction()
        {
            if(_productionPrepared)return;
            _productionSession.Clear();
            var repository=new ProductionLayoutRepository();
            var paths=repository.GetPaths(_locationId);
            var robots=repository.GetRobots(_locationId);
            var options=new PathAnimationOptions
            {
                Duration=TimeSpan.FromSeconds(2),
                InitialScale=.73,
                AutoStart=false
            };
            foreach(var path in paths)
            {
                var control=new ProductUC(path.PartImagePath??string.Empty);
                var definition=new PathAnimationDefinition(path.PathName,path.PartName,path.PathData,
                    path.PickupRobotName??string.Empty,
                    string.IsNullOrWhiteSpace(path.PickupRobotName)?ProductionAction.None:ProductionAction.Pickup);
                _productionSession.Add(GameAnimationHelper.AddControlOnPath(definition,_view.MainCanvas,control,options));
            }
            foreach(var configuration in robots)
            {
                var robot=_view.LoadedRobotArms.FirstOrDefault(candidate=>
                    string.Equals(candidate.AnimationTargetName,configuration.RobotName,StringComparison.OrdinalIgnoreCase));
                if(robot!=null)
                {
                    robot.ReleasePartAtDrop=configuration.ReleasePartAtDrop;
                    robot.OutputPartImagePath=configuration.OutputPartImagePath;
                }
                if(!string.IsNullOrWhiteSpace(configuration.DropPathName))
                    _productionSession.AddDropHandoff(configuration.RobotName,configuration.DropPathName);
            }
            _productionPrepared=true;
        }
        



    }
}
