using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.ViewModels.Locations;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.FactoryControls;
using CatoriUCLibrary.Views.Person;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    public class Locationinterior3SubController : LocationSubControllerBase, ILocationSubController
    {
        ProductUC paintBottles3_part42_productUC;
        PathAnimationHandle _pathHandlerCrunLeft;
        ProductUC unassigned_part43_productUC;
        PathAnimationHandle _pathHandlerCMidL;
        ProductUC paintBrush3_part44_productUC;
        PathAnimationHandle _pathHandlerCMidR;
        ProductUC unassigned_part45_productUC;
        PathAnimationHandle _pathHandlerCRunR;
        ProductUC robotMover_part46_productUC;
        PathAnimationHandle _pathHandlerRobotMover;
        ProductUC droneEmpty_part47_productUC;
        PathAnimationHandle _pathHandlerDroneDelivery;
        // ============================================================
        //  GENERATED BY CATORI.STUDIO.DEV
        //
        //  DO NOT FIX GENERATED CODE HERE.
        //
        //  If this code is incorrect, fix the generator in Studio
        //  and regenerate this file.
        // ============================================================
        // Call SetupFactoryPeople(); before SetupFactoryControlPanels().
        private PersonUC? _personActive;
        private FactoryControlPanelUC? _factoryPanel;

        private void SetupFactoryPeople()
        {
            try
            {
                _personActive = new PersonUC
                {
                    Name = "PersonActive",
                    Width = 128.89990089197227,
                    Height = 171.86653452262965,
                    CurrentActivity = PersonActivity.Idle,
                    IsDragEnabled = true,
                    IsArmEditingEnabled = true
                };
                Canvas.SetLeft(_personActive, 1533.2738486647982);
                Canvas.SetTop(_personActive, 312.9763984479716);
                Panel.SetZIndex(_personActive, 1224);
                _view.MainCanvas.Children.Add(_personActive);

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
                _factoryPanel = new FactoryControlPanelUC
                {
                    Name = "FactoryPanel",
                    Width = 118.9593657086225,
                    Height = 142.751238850347,
                    Mode = FactoryControlPanelMode.Lever,
                    AnimationTargetName = "",
                    ActivationRadius = 65,
                    IsDragEnabled = false,
                    TargetPerson = _personActive
                };
                Canvas.SetLeft(_factoryPanel, 1760.8835066003114);
                Canvas.SetTop(_factoryPanel, 376.9985926631572);
                Panel.SetZIndex(_factoryPanel, 1223);
                _view.MainCanvas.Children.Add(_factoryPanel);

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }

        public Locationinterior3SubController(FactoryInterior_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            SetupAnimations();
            SetupFactoryPeople();
            SetupFactoryControlPanels();
        }

        // ============================================================
        //  GENERATED BY CATORI.STUDIO.DEV
        //
        //  DO NOT FIX GENERATED CODE HERE.
        //
        //  If this code is incorrect, fix the generator in Studio
        //  and regenerate this file.
        // ============================================================
        private void SetupAnimations()
        {
            try
            {
                var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
                var productionPaths = new ProductionLayoutRepository().GetPaths(_locationId)
                    .ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);

                var options = new PathAnimationOptions
                {
                    Duration = TimeSpan.FromSeconds(2),
                    InitialScale = .73,
                    AutoStart = false
                };
                var droneOptions = new PathAnimationOptions
                {
                    Duration = TimeSpan.FromSeconds(2),
                    InitialScale = .73,
                    AutoStart = false,
                    RotateWithPath = false,
                    ControlWidth = 100,
                    ControlHeight = 100
                };

                productionPaths.TryGetValue("CrunLeft", out var productionPathCrunLeft);
                paintBottles3_part42_productUC = new ProductUC(productionPathCrunLeft?.PartImagePath ?? string.Empty);
                var layoutItem42 = GetLayoutItem(layoutItems, "CrunLeft");
                _pathHandlerCrunLeft = GameAnimationHelper.AddControlOnPath(
                    "CrunLeft", productionPathCrunLeft?.PartName ?? "PaintBottles3", "Robot4", "Pickup",
                    _view.MainCanvas, paintBottles3_part42_productUC, layoutItem42.ItemDataJson ?? string.Empty, options);
                _productionSession.Add(_pathHandlerCrunLeft);
                _productionSession.AddDeferredPath("CrunLeft");

                productionPaths.TryGetValue("CMidL", out var productionPathCMidL);
                unassigned_part43_productUC = new ProductUC(productionPathCMidL?.PartImagePath ?? string.Empty);
                var layoutItem43 = GetLayoutItem(layoutItems, "CMidL");
                _pathHandlerCMidL = GameAnimationHelper.AddControlOnPath(
                    "CMidL", productionPathCMidL?.PartName ?? "CMidLPart", "robot4", "Pickup",
                    _view.MainCanvas, unassigned_part43_productUC, layoutItem43.ItemDataJson ?? string.Empty, options);
                _productionSession.Add(_pathHandlerCMidL);

                productionPaths.TryGetValue("CMidR", out var productionPathCMidR);
                paintBrush3_part44_productUC = new ProductUC(productionPathCMidR?.PartImagePath ?? string.Empty);
                var layoutItem44 = GetLayoutItem(layoutItems, "CMidR");
                _pathHandlerCMidR = GameAnimationHelper.AddControlOnPath(
                    "CMidR", productionPathCMidR?.PartName ?? "PaintBrush3", "robot3", "Pickup",
                    _view.MainCanvas, paintBrush3_part44_productUC, layoutItem44.ItemDataJson ?? string.Empty, options);
                _productionSession.Add(_pathHandlerCMidR);

                productionPaths.TryGetValue("CRunR", out var productionPathCRunR);
                unassigned_part45_productUC = new ProductUC(productionPathCRunR?.PartImagePath ?? string.Empty);
                var layoutItem45 = GetLayoutItem(layoutItems, "CRunR");
                _pathHandlerCRunR = GameAnimationHelper.AddControlOnPath(
                    "CRunR", productionPathCRunR?.PartName ?? "CRunRPart", "DroneDelivery", "StartPath",
                    _view.MainCanvas, unassigned_part45_productUC, layoutItem45.ItemDataJson ?? string.Empty, options);
                _productionSession.Add(_pathHandlerCRunR);
                _productionSession.AddDeferredPath("CRunR");

                productionPaths.TryGetValue("RobotMover", out var productionPathRobotMover);
                robotMover_part46_productUC = new ProductUC(productionPathRobotMover?.PartImagePath ?? string.Empty);
                robotMover_part46_productUC.Width = 100;
                robotMover_part46_productUC.Height = 100;
                var layoutItem46 = GetLayoutItem(layoutItems, "RobotMover");
                _pathHandlerRobotMover = GameAnimationHelper.AddControlOnPath(
                    "RobotMover", productionPathRobotMover?.PartName ?? "RobotMover", "CrunLeft", "StartPath",
                    _view.MainCanvas, robotMover_part46_productUC, layoutItem46.ItemDataJson ?? string.Empty, options);
                _productionSession.Add(_pathHandlerRobotMover);

                productionPaths.TryGetValue("DroneDelivery", out var productionPathDroneDelivery);
                droneEmpty_part47_productUC = new ProductUC(productionPathDroneDelivery?.PartImagePath ?? string.Empty);
                var layoutItem47 = GetLayoutItem(layoutItems, "DroneDelivery");
                _pathHandlerDroneDelivery = GameAnimationHelper.AddControlOnPath(
                    "DroneDelivery", productionPathDroneDelivery?.PartName ?? "DroneEmpty", "", "",
                    _view.MainCanvas, droneEmpty_part47_productUC, layoutItem47.ItemDataJson ?? string.Empty, droneOptions);
                _productionSession.Add(_pathHandlerDroneDelivery);
                _productionSession.AddDeferredPath("DroneDelivery");

                _productionSession.AddDropHandoff("Robot4", "CMidL");
                _productionSession.AddDropHandoff("robot4", "CMidR");
                _productionSession.AddDropHandoff("robot3", "CRunR");
                _productionSession.AddPathHandoff("RobotMover", "CrunLeft", TimeSpan.Zero);
                _productionSession.AddPathHandoff("CRunR", "DroneDelivery", TimeSpan.Zero);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        private LocationLayoutItemViewModel GetLayoutItem(
            IEnumerable<LocationLayoutItemViewModel> layoutItems, string itemName)
            => layoutItems.FirstOrDefault(item =>
                   string.Equals(item.ItemName, itemName, StringComparison.Ordinal))
               ?? throw new InvalidOperationException(
                   $"Layout item '{itemName}' was not found in Factory 3.");

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine(
                $"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
        }

        public void StartProduction()
        {
            ConfigureProductionRobots();
            _productionSession.StartRoots();
        }

        private void ConfigureProductionRobots()
        {
            foreach (var configuration in new ProductionLayoutRepository().GetRobots(_locationId))
            {
                var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                    string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
                if (robot == null) continue;
                robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
                robot.OutputPartImagePath = configuration.OutputPartImagePath;
            }
        }

        public void StopProduction() => _productionSession.StopAll();

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
