// ============================================================
//  GENERATED BY CATORI.STUDIO.DEV
//
//  DO NOT FIX GENERATED CODE HERE.
//
//  If this code is incorrect, fix the generator in Studio
//  and regenerate this file.
// ============================================================
//  CODE GENERATION VERSION: 96

using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Objects.Hotspots;
using CatoriServices.Objects.database.Production;
using CatoriUCLibrary.Views.FactoryControls;
using CatoriUCLibrary.Views.Person;
using CatoriUCLibrary.Views.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Controls;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    // Generated by Catori.Studio.Dev, generation 96. Regenerate in Studio; do not edit by hand.
    [System.CodeDom.Compiler.GeneratedCode("Catori.Studio.Dev", "96")]
    public partial class toreGrocery1SubController : LocationSubControllerBase, ILocationSubController
    {
        public const long GeneratedCodeVersion = 96;

        partial void OnGeneratedLocationInitialized();
        partial void OnGeneratedProductionStarted();
        partial void OnGeneratedProductionStopping();
        partial void OnGeneratedAnimationCompleted(AnimationCompleteMessage message);

        // Generated code for location layout items

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
        };
        private readonly PathAnimationSession _productionSession = new();

        private void SetupAnimations()
        {
            try
            {
        var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("toreGrocery1").GetAwaiter().GetResult()
            ?? throw new InvalidOperationException("Location 'toreGrocery1' was not found in the game database. Export the Studio location before running generated code.");
        _locationId = generatedLocation.LocationId;
        var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
        var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
        PathAnimationOptions ? options = new PathAnimationOptions();
        options.Duration = TimeSpan.FromSeconds(2);
        options.InitialScale = .73;
        options.AutoStart = false;
        PathAnimationOptions droneOptions = new PathAnimationOptions();
        droneOptions.Duration = TimeSpan.FromSeconds(2);
        droneOptions.InitialScale = .73;
        droneOptions.AutoStart = false;
        droneOptions.RotateWithPath = false;
        droneOptions.ControlWidth = 100;
        droneOptions.ControlHeight = 100;
        foreach (var task in _robotTasks)
            if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                case ProductionAction.StartPath:
                    // PathAnimationSession starts the configured target with its assigned control.
                    break;
                case ProductionAction.TransitionToView:
                    _ = TransitionToLocationViewAsync(message.TargetName);
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
            OnGeneratedAnimationCompleted(message);
        }
        // Call SetupPeople(); before SetupFactoryControlPanels().
        private PersonUC? _personActive;

        private void SetupPeople()
        {
            try
            {
                _personActive = _view.MainCanvas.Children.OfType<PersonUC>().FirstOrDefault(person =>
                    string.Equals(person.ToolTip as string, "PersonActive", StringComparison.OrdinalIgnoreCase))
                    ?? CatoriApp.Core.Objects.Shared.GlobalAllApps.GetPerson(new CatoriApp.Core.Objects.Shared.PersonMetadata(
                        "PersonActive",
                        300,
                        400,
                        PersonActivity.Idle,
                        true,
                        true,
                        "",
                        PersonRole.Avatar));
                _personActive.ToolTip = "PersonActive";
                Canvas.SetLeft(_personActive, 810);
                Canvas.SetTop(_personActive, 500);
                Panel.SetZIndex(_personActive, 2200);
                if (_personActive.Parent == null)
                {
                    _view.MainCanvas.Children.Add(_personActive);
                }

            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }
        // No factory control panels are configured for this location.

        public toreGrocery1SubController(Location_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            InitializeLocationFeature("static airplanes", SetupStaticAirplanes);
            InitializeLocationFeature("people", SetupPeople);
            InitializeLocationFeature("factory control panels", SetupFactoryControlPanels);
            InitializeLocationFeature("path animations", SetupAnimations);
            InitializeLocationFeature("hotspots", () =>
                HotspotLayer.Attach(_view.MainCanvas, LoadLayoutItemsNow(), _view, _productionSession.StartPath));
            OnGeneratedLocationInitialized();
        }

        public void StartProduction()
        {
        var robotConfigurations = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetRobots(_locationId);
        foreach (var configuration in robotConfigurations)
        {
            var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
            if (robot == null) continue;
            robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
            robot.OutputPartImagePath = configuration.OutputPartImagePath;
        }
        _productionSession.StartRoots();
        OnGeneratedProductionStarted();
        }

        public void StopProduction()
        {
            OnGeneratedProductionStopping();
            _productionSession.StopAll();
        }

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
