-- Generated by LayoutDesignerTool
-- Generic image layout script. No game project reference required.

CREATE TABLE IF NOT EXISTS ImageLayouts (
    image_layout_id INTEGER PRIMARY KEY AUTOINCREMENT,
    layout_name TEXT NOT NULL,
    background_image_path TEXT NULL,
    canvas_width REAL NOT NULL,
    canvas_height REAL NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS ImageLayoutElements (
    image_layout_element_id INTEGER PRIMARY KEY AUTOINCREMENT,
    image_layout_id INTEGER NOT NULL,
    element_key TEXT NOT NULL,
    element_name TEXT NOT NULL,
    element_type TEXT NOT NULL,
    x REAL NOT NULL DEFAULT 0,
    y REAL NOT NULL DEFAULT 0,
    width REAL NOT NULL DEFAULT 0,
    height REAL NOT NULL DEFAULT 0,
    rotation_degrees REAL NOT NULL DEFAULT 0,
    z_index INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NULL,
    FOREIGN KEY (image_layout_id) REFERENCES ImageLayouts(image_layout_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ImageLayoutPoints (
    image_layout_point_id INTEGER PRIMARY KEY AUTOINCREMENT,
    image_layout_element_id INTEGER NOT NULL,
    point_index INTEGER NOT NULL,
    point_role TEXT NULL,
    x REAL NOT NULL,
    y REAL NOT NULL,
    segment_kind TEXT NOT NULL DEFAULT 'Line',
    FOREIGN KEY (image_layout_element_id) REFERENCES ImageLayoutElements(image_layout_element_id) ON DELETE CASCADE
);

BEGIN TRANSACTION;

INSERT INTO ImageLayouts (layout_name, background_image_path, canvas_width, canvas_height)
VALUES ('Image Layout', 'C:\Development\Gaming\Catori2026\Catori_2026_v1\Images\FactoryInteriors\FactoryInterior1.png', 1920, 1080);

CREATE TEMP TABLE IF NOT EXISTS _layout_designer_layout_id (image_layout_id INTEGER NOT NULL);
DELETE FROM _layout_designer_layout_id;
INSERT INTO _layout_designer_layout_id (image_layout_id) VALUES (last_insert_rowid());

CREATE TEMP TABLE IF NOT EXISTS _layout_designer_ids (element_key TEXT PRIMARY KEY, image_layout_element_id INTEGER NOT NULL);
DELETE FROM _layout_designer_ids;

INSERT INTO ImageLayoutElements
    (image_layout_id, element_key, element_name, element_type, x, y, rotation_degrees, z_index, metadata_json)
VALUES
    ((SELECT image_layout_id FROM _layout_designer_layout_id), '5de21827a144499ab1892928fa4f4a26', 'Conveyor 1', 'Conveyor', 0, 0,  0, 1, '{"designer":"conveyor-path"}');

INSERT INTO _layout_designer_ids (element_key, image_layout_element_id) VALUES ('5de21827a144499ab1892928fa4f4a26', last_insert_rowid());

INSERT INTO ImageLayoutPoints (image_layout_element_id, point_index, point_role, x, y, segment_kind)
VALUES ((SELECT image_layout_element_id FROM _layout_designer_ids WHERE element_key = '5de21827a144499ab1892928fa4f4a26'), 0, 'Start', 1514.278, 530.796, 'Line');

INSERT INTO ImageLayoutPoints (image_layout_element_id, point_index, point_role, x, y, segment_kind)
VALUES ((SELECT image_layout_element_id FROM _layout_designer_ids WHERE element_key = '5de21827a144499ab1892928fa4f4a26'), 1, 'Path', 476.353, 783.393, 'Line');

INSERT INTO ImageLayoutPoints (image_layout_element_id, point_index, point_role, x, y, segment_kind)
VALUES ((SELECT image_layout_element_id FROM _layout_designer_ids WHERE element_key = '5de21827a144499ab1892928fa4f4a26'), 2, 'Path', 688.248, 825.294, 'Line');

INSERT INTO ImageLayoutPoints (image_layout_element_id, point_index, point_role, x, y, segment_kind)
VALUES ((SELECT image_layout_element_id FROM _layout_designer_ids WHERE element_key = '5de21827a144499ab1892928fa4f4a26'), 3, 'Path', 1566.953, 529.599, 'Line');

INSERT INTO ImageLayoutPoints (image_layout_element_id, point_index, point_role, x, y, segment_kind)
VALUES ((SELECT image_layout_element_id FROM _layout_designer_ids WHERE element_key = '5de21827a144499ab1892928fa4f4a26'), 4, 'Path', 1520.264, 518.824, 'Line');

DROP TABLE _layout_designer_layout_id;
DROP TABLE _layout_designer_ids;
COMMIT;
