// ============================================================
//  GENERATED BY CATORI.STUDIO.DEV
//
//  DO NOT FIX GENERATED CODE HERE.
//
//  If this code is incorrect, fix the generator in Studio
//  and regenerate this file.
// ============================================================
//  CODE GENERATION VERSION: 86

using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Objects.Hotspots;
using CatoriShared.AnimationHelpersTest;
using CatoriUCLibrary.Views.Airplane;

namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    // Generated by Catori.Studio.Dev, generation 86. Regenerate in Studio; do not edit by hand.
    [System.CodeDom.Compiler.GeneratedCode("Catori.Studio.Dev", "86")]
    public partial class BeachAirportSubController : LocationSubControllerBase, ILocationSubController
    {
        public const long GeneratedCodeVersion = 86;

        partial void OnGeneratedLocationInitialized();
        partial void OnGeneratedProductionStarted();
        partial void OnGeneratedProductionStopping();
        partial void OnGeneratedAnimationCompleted(AnimationCompleteMessage message);

        // Generated code for location layout items
        FrameworkElement unassigned_part84_productUC;
        PathAnimationHandleTest _pathHandlerStartPath;
        FrameworkElement unassigned_part85_productUC;
        PathAnimationHandleTest _pathHandlerLandingPath;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
        };
        private readonly PathAnimationSessionTest _productionSession = new();

        private void SetupAnimations(AirplaneUC? airplane)
        {
            try
            {
        var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("BeachAirport").GetAwaiter().GetResult()
            ?? throw new InvalidOperationException("Location 'BeachAirport' was not found in the game database. Export the Studio location before running generated code.");
        _locationId = generatedLocation.LocationId;
        var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
        var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
        CatoriShared.AnimationHelpers.PathAnimationOptions? options = new CatoriShared.AnimationHelpers.PathAnimationOptions();
        options.Duration = TimeSpan.FromSeconds(2);
        options.InitialScale = 1;
        options.AutoStart = false;
        CatoriShared.AnimationHelpers.PathAnimationOptions droneOptions = new CatoriShared.AnimationHelpers.PathAnimationOptions();
        droneOptions.Duration = TimeSpan.FromSeconds(2);
        droneOptions.InitialScale = 1;
        droneOptions.AutoStart = false;
        droneOptions.RotateWithPath = false;
        droneOptions.ControlWidth = 100;
        droneOptions.ControlHeight = 100;
        productionPaths.TryGetValue("StartPath", out var productionPathStartPath);
        // WARNING: StartPath has no dropped product assignment.
        // WARNING: StartPath is not connected to a robot.
        unassigned_part84_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathStartPath?.PartImagePath) ? "" : productionPathStartPath.PartImagePath);
        var optionsStartPath = new CatoriShared.AnimationHelpers.PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = false, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = 1
        };
        // Code for Layout Item: StartPath
        var layoutItem84 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "StartPath", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 84)
            ?? throw new InvalidOperationException($"Layout item 'StartPath' was not found in location {_locationId}.");
        _pathHandlerStartPath = GameAnimationHelperTest.AddControlOnPath("StartPath", string.IsNullOrWhiteSpace(productionPathStartPath?.PartName) ? "StartPathPart" : productionPathStartPath.PartName, "LandingPath", "StartPath", _view.MainCanvas,
            airplane, layoutItem84.ItemDataJson ?? string.Empty, optionsStartPath);

        _productionSession.Add(_pathHandlerStartPath);
        productionPaths.TryGetValue("LandingPath", out var productionPathLandingPath);
        // WARNING: LandingPath has no dropped product assignment.
        // WARNING: LandingPath is not connected to a robot.
        unassigned_part85_productUC = new ProductUC(string.IsNullOrWhiteSpace(productionPathLandingPath?.PartImagePath) ? "" : productionPathLandingPath.PartImagePath);
        var optionsLandingPath = new CatoriShared.AnimationHelpers.PathAnimationOptions {
            Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
            RotateWithPath = false, AutoReverse = false,
            SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
            ZIndex = 2002, InitialScale = 1, ControlWidth = 100, ControlHeight = 100
        };
        // Code for Layout Item: LandingPath
        var layoutItem85 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "LandingPath", StringComparison.OrdinalIgnoreCase))
            ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 85)
            ?? throw new InvalidOperationException($"Layout item 'LandingPath' was not found in location {_locationId}.");
        _pathHandlerLandingPath = GameAnimationHelperTest.AddControlOnPath("LandingPath", string.IsNullOrWhiteSpace(productionPathLandingPath?.PartName) ? "LandingPathPart" : productionPathLandingPath.PartName, "", "", _view.MainCanvas,
            airplane, layoutItem85.ItemDataJson ?? string.Empty, optionsLandingPath);

        _productionSession.Add(_pathHandlerLandingPath);
        _productionSession.AddDeferredPath("LandingPath");
        _productionSession.AddPathHandoff("StartPath", "LandingPath", TimeSpan.FromSeconds(0));
        foreach (var task in _robotTasks)
            if (!string.IsNullOrWhiteSpace(task.DropPath)) _productionSession.AddDropHandoff(task.RobotName, task.DropPath);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                case ProductionAction.StartPath:
                    // PathAnimationSession starts the configured target with its assigned control.
                    break;
                case ProductionAction.TransitionToView:
                    _ = TransitionToLocationViewAsync(message.TargetName);
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
            OnGeneratedAnimationCompleted(message);
        }
        // Call SetupPeople(); before SetupFactoryControlPanels().

        private void SetupPeople()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }
        // No factory control panels are configured for this location.
        // No people are configured for this location.

        public BeachAirportSubController(Location_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _locationId = locationId;
            InitializeLocationFeature("static airplanes", SetupStaticAirplanes);
            AirplaneUC? airplane = _view.MainCanvas.Children
             .OfType<AirplaneUC>().FirstOrDefault();
            if (airplane != null)
            {
                const double beachAirportScale = 1.15;
                double originalWidth = airplane.Width;
                double originalHeight = airplane.Height;
                double scaledWidth = originalWidth * beachAirportScale;
                double scaledHeight = originalHeight * beachAirportScale;
                Canvas.SetLeft(airplane, Canvas.GetLeft(airplane) - (scaledWidth - originalWidth) / 2);
                Canvas.SetTop(airplane, Canvas.GetTop(airplane) - (scaledHeight - originalHeight) / 2);
                airplane.Width = scaledWidth;
                airplane.Height = scaledHeight;
            }
            InitializeLocationFeature("people", SetupPeople);
            InitializeLocationFeature("factory control panels", SetupFactoryControlPanels);
            InitializeLocationFeature("path animations", () => SetupAnimations(airplane));  
            InitializeLocationFeature("hotspots", () =>
                HotspotLayer.Attach(_view.MainCanvas, LoadLayoutItemsNow(), _view, _productionSession.StartPath));
            OnGeneratedLocationInitialized();
            _productionSession.StartRoots();
        }

        public void StartAnimation()
        {
        var robotConfigurations = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetRobots(_locationId);
        foreach (var configuration in robotConfigurations)
        {
            var robot = _view.LoadedRobotArms.FirstOrDefault(candidate =>
                string.Equals(candidate.AnimationTargetName, configuration.RobotName, StringComparison.Ordinal));
            if (robot == null) continue;
            robot.ReleasePartAtDrop = configuration.ReleasePartAtDrop;
            robot.OutputPartImagePath = configuration.OutputPartImagePath;
        }
        _productionSession.StartRoots();
        OnGeneratedProductionStarted();
        }

        public void StopProduction()
        {
            OnGeneratedProductionStopping();
            _productionSession.StopAll();
        }

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
