// ============================================================
//  GENERATED BY CATORI.STUDIO.DEV
//
//  DO NOT FIX GENERATED CODE HERE.
//
//  If this code is incorrect, fix the generator in Studio
//  and regenerate this file.
// ============================================================
//  CODE GENERATION VERSION: 87

using CatoriApp.Core.Objects.Production;
using CatoriApp.Game.Objects.AnimationOnPath;
using CatoriApp.Game.Objects.Hotspots;
using CatoriShared.AnimationHelpersTest;
using CatoriUCLibrary.Views.Airplane;
namespace CatoriApp.Game.Controllers.LocationSubControllers
{
    // Generated by Catori.Studio.Dev, generation 87. Regenerate in Studio; do not edit by hand.
    [System.CodeDom.Compiler.GeneratedCode("Catori.Studio.Dev", "87")]
    public partial class BeachFlyoverSubController : LocationSubControllerBase, ILocationSubController
    {
        public const long GeneratedCodeVersion = 87;

        partial void OnGeneratedLocationInitialized();
        partial void OnGeneratedProductionStarted();
        partial void OnGeneratedProductionStopping();
        partial void OnGeneratedAnimationCompleted(AnimationCompleteMessage message);

        // Generated code for location layout items
        PathAnimationHandleTest _pathHandlerFlyingPath;
        PathAnimationSessionTest _productionSession;

        private readonly record struct GeneratedRobotTask(string RobotName, string? PickupPath, string? DropPath, double[][] Poses);
        private readonly List<GeneratedRobotTask> _robotTasks = new()
        {
        };

        private void SetupAnimations(AirplaneUC? airplane)
        {
            try
            {
                var generatedLocation = new CatoriServices.Objects.database.Locations.LocationRepository().GetByNameAsync("BeachFlyover").GetAwaiter().GetResult()
                    ?? throw new InvalidOperationException("Location 'BeachFlyover' was not found in the game database. Export the Studio location before running generated code.");
                _locationId = generatedLocation.LocationId;
                var layoutItems = _layoutItemService.GetByLocationIdAsync(_locationId).GetAwaiter().GetResult();
                var productionPaths = new CatoriServices.Objects.database.Production.ProductionLayoutRepository().GetPaths(_locationId).ToDictionary(path => path.PathName, StringComparer.OrdinalIgnoreCase);
                        CatoriShared.AnimationHelpers.PathAnimationOptions? options = new CatoriShared.AnimationHelpers.PathAnimationOptions();
                options.Duration = TimeSpan.FromSeconds(2);
                options.InitialScale = .73;
                options.AutoStart = false;
                        CatoriShared.AnimationHelpers.PathAnimationOptions droneOptions = new CatoriShared.AnimationHelpers.PathAnimationOptions();
                droneOptions.Duration = TimeSpan.FromSeconds(2);
                droneOptions.InitialScale = .73;
                droneOptions.AutoStart = false;
                droneOptions.RotateWithPath = false;
                droneOptions.ControlWidth = 100;
                droneOptions.ControlHeight = 100;
                productionPaths.TryGetValue("FlyingPath", out var productionPathFlyingPath);
                // Assigned Studio component: AirplaneSide
                // WARNING: FlyingPath is not connected to a robot.
                var optionsFlyingPath = new CatoriShared.AnimationHelpers.PathAnimationOptions {
                    Duration = TimeSpan.FromSeconds(2), StartDelay = TimeSpan.FromSeconds(0), AutoStart = false,
                    RotateWithPath = false, AutoReverse = false,
                    SpeedRatio = 1, AccelerationRatio = 0, DecelerationRatio = 0,
                    ZIndex = 2002, InitialScale = .73, ControlWidth = 100, ControlHeight = 100
                };
                // Code for Layout Item: FlyingPath
                var layoutItem79 = layoutItems.FirstOrDefault(item => string.Equals(item.ItemName, "FlyingPath", StringComparison.OrdinalIgnoreCase))
                    ?? layoutItems.FirstOrDefault(item => item.LocationLayoutItemId == 79)
                    ?? throw new InvalidOperationException($"Layout item 'FlyingPath' was not found in location {_locationId}.");
                _pathHandlerFlyingPath = GameAnimationHelperTest.AddControlOnPath("FlyingPath", string.IsNullOrWhiteSpace(productionPathFlyingPath?.PartName) ? "AirplaneSide" : productionPathFlyingPath.PartName, "BeachTravel3", "TransitionToView", _view.MainCanvas,
                    airplane, layoutItem79.ItemDataJson ?? string.Empty, optionsFlyingPath);

                _productionSession.Add(_pathHandlerFlyingPath);
             }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupAnimations failed: {ex}");
                throw;
            }
        }

        protected override void OnAnimationCompleted(AnimationCompleteMessage message)
        {
            switch (message.Action)
            {
                case ProductionAction.None:
                    break;
                case ProductionAction.Pickup:
                    break;
                case ProductionAction.Drop:
                    break;
                case ProductionAction.DronePickup:
                    break;
                case ProductionAction.StartPath:
                    // PathAnimationSession starts the configured target with its assigned control.
                    break;
                case ProductionAction.TransitionToView:
                    _ = TransitionToLocationViewAsync(message.TargetName);
                    break;
                default:
                    break;
            }
            System.Diagnostics.Debug.WriteLine($"Animation completed: {message.AnimationName}; part: {message.PartName}; action: {message.Action}");
            OnGeneratedAnimationCompleted(message);
        }
        // Call SetupPeople(); before SetupFactoryControlPanels().

        private void SetupPeople()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupPeople failed: {ex}");
                throw;
            }
        }

        private void SetupFactoryControlPanels()
        {
            try
            {
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"SetupFactoryControlPanels failed: {ex}");
                throw;
            }
        }
        // No factory control panels are configured for this location.
        // No people are configured for this location.

        public BeachFlyoverSubController(Location_UC view, long locationId)
            : base(locationId, view)
        {
            base._view = view;
            _productionSession = new PathAnimationSessionTest();
            _locationId = locationId;
            InitializeLocationFeature("static airplanes", SetupStaticAirplanes);
            InitializeLocationFeature("people", SetupPeople);
            AirplaneUC? airplane = _view.MainCanvas.Children
                .OfType<AirplaneUC>().FirstOrDefault();
            InitializeLocationFeature("factory control panels", SetupFactoryControlPanels);
            InitializeLocationFeature("path animations", () => SetupAnimations(airplane));
            InitializeLocationFeature("hotspots", () =>
                HotspotLayer.Attach(_view.MainCanvas, LoadLayoutItemsNow(), _view, _productionSession.StartPath));
            OnGeneratedLocationInitialized();
            _productionSession.StartRoots();

        }

        public void StartAnimation()
        {
      
        _productionSession.StartRoots();
        OnGeneratedProductionStarted();
        }

        public void StopProduction()
        {
            OnGeneratedProductionStopping();
            _productionSession.StopAll();
        }

        public void LoadPaths()
        {
            // Paths are loaded by SetupAnimations.
        }

        public void OnAnimationCompleted()
        {
        }
    }
}
